version: "3.3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${APP_IMAGE}"
    # volumes: 
    #  - ./uffizzi/entrypoint.sh:/acme.sh-docker.sh:ro
    #  - ./acme.sh:/acme.sh
    ports:
    - "7700:7700"
    - "7681:7681"
    entrypoint: ["bin/sh", "-c"]
    command: ["ttyd /entry.sh tui"]
    deploy:
      resources:
        limits:
          memory: 2000M
